default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  schema_search_path: 'public'
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DB_PORT") { '5432' } %>
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>

development:
  <<: *default
  database: granite_try_dev

test:
  <<: *default
  database: granite_try_test

production:
  <<: *default
  database: granite_try_dev
